// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Configcat
{
    public static class GetProducts
    {
        /// <summary>
        /// ## # configcat.getProducts Resource
        /// 
        /// Use this data source to access information about existing **Products**. [What is a Product in ConfigCat?](https://configcat.com/docs/main-concepts)
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Configcat = Pulumi.Configcat;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myProducts = Configcat.GetProducts.Invoke(new()
        ///     {
        ///         NameFilterRegex = "ConfigCat's product",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["productId"] = myProducts.Apply(getProductsResult =&gt; getProductsResult.Products[0]?.ProductId),
        ///     };
        /// });
        /// ```
        /// 
        /// ## Endpoints used
        /// 
        /// - [List Products](https://api.configcat.com/docs/#tag/Products/operation/get-products)
        /// </summary>
        public static Task<GetProductsResult> InvokeAsync(GetProductsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetProductsResult>("configcat:index/getProducts:getProducts", args ?? new GetProductsArgs(), options.WithDefaults());

        /// <summary>
        /// ## # configcat.getProducts Resource
        /// 
        /// Use this data source to access information about existing **Products**. [What is a Product in ConfigCat?](https://configcat.com/docs/main-concepts)
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Configcat = Pulumi.Configcat;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var myProducts = Configcat.GetProducts.Invoke(new()
        ///     {
        ///         NameFilterRegex = "ConfigCat's product",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["productId"] = myProducts.Apply(getProductsResult =&gt; getProductsResult.Products[0]?.ProductId),
        ///     };
        /// });
        /// ```
        /// 
        /// ## Endpoints used
        /// 
        /// - [List Products](https://api.configcat.com/docs/#tag/Products/operation/get-products)
        /// </summary>
        public static Output<GetProductsResult> Invoke(GetProductsInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetProductsResult>("configcat:index/getProducts:getProducts", args ?? new GetProductsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetProductsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Filter the Products by name.
        /// </summary>
        [Input("nameFilterRegex")]
        public string? NameFilterRegex { get; set; }

        public GetProductsArgs()
        {
        }
        public static new GetProductsArgs Empty => new GetProductsArgs();
    }

    public sealed class GetProductsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Filter the Products by name.
        /// </summary>
        [Input("nameFilterRegex")]
        public Input<string>? NameFilterRegex { get; set; }

        public GetProductsInvokeArgs()
        {
        }
        public static new GetProductsInvokeArgs Empty => new GetProductsInvokeArgs();
    }


    [OutputType]
    public sealed class GetProductsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string? NameFilterRegex;
        /// <summary>
        /// A product list block defined as below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetProductsProductResult> Products;

        [OutputConstructor]
        private GetProductsResult(
            string id,

            string? nameFilterRegex,

            ImmutableArray<Outputs.GetProductsProductResult> products)
        {
            Id = id;
            NameFilterRegex = nameFilterRegex;
            Products = products;
        }
    }
}
