// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Configcat
{
    /// <summary>
    /// Creates and manages a **Segment**. [What is a Segment in ConfigCat?](https://configcat.com/docs/advanced/segments)
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Configcat = Pulumiverse.Configcat;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var config = new Config();
    ///     var productId = config.Require("productId");
    ///     var mySegment = new Configcat.Segment("my_segment", new()
    ///     {
    ///         ProductId = productId,
    ///         Name = "Beta users",
    ///         Description = "Beta users' description",
    ///         ComparisonAttribute = "email",
    ///         Comparator = "sensitiveIsOneOf",
    ///         ComparisonValue = "betauser1@example.com,betauser2@example.com",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["segmentId"] = mySegment.Id,
    ///     };
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Segments can be imported using the SegmentId. Get the SegmentId using the [List Segments API](https://api.configcat.com/docs/#tag/Segments/operation/get-segments) for example.
    /// 
    /// ```sh
    /// $ pulumi import configcat:index/segment:Segment example 08d86d63-2726-47cd-8bfc-59608ecb91e2
    /// ```
    /// </summary>
    [ConfigcatResourceType("configcat:index/segment:Segment")]
    public partial class Segment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The [comparator](https://configcat.com/docs/advanced/targeting/#comparator) of the Segment.
        /// </summary>
        [Output("comparator")]
        public Output<string> Comparator { get; private set; } = null!;

        /// <summary>
        /// The [comparison attribute](https://configcat.com/docs/advanced/targeting/#attribute) of the Segment.
        /// </summary>
        [Output("comparisonAttribute")]
        public Output<string> ComparisonAttribute { get; private set; } = null!;

        /// <summary>
        /// The [comparison value](https://configcat.com/docs/advanced/targeting/#comparison-value) of the Segment.
        /// </summary>
        [Output("comparisonValue")]
        public Output<string> ComparisonValue { get; private set; } = null!;

        /// <summary>
        /// The description of the Segment.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// The name of the Segment.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The ID of the Product.
        /// </summary>
        [Output("productId")]
        public Output<string> ProductId { get; private set; } = null!;


        /// <summary>
        /// Create a Segment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Segment(string name, SegmentArgs args, CustomResourceOptions? options = null)
            : base("configcat:index/segment:Segment", name, args ?? new SegmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Segment(string name, Input<string> id, SegmentState? state = null, CustomResourceOptions? options = null)
            : base("configcat:index/segment:Segment", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "api://github.com/pulumiverse",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Segment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Segment Get(string name, Input<string> id, SegmentState? state = null, CustomResourceOptions? options = null)
        {
            return new Segment(name, id, state, options);
        }
    }

    public sealed class SegmentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The [comparator](https://configcat.com/docs/advanced/targeting/#comparator) of the Segment.
        /// </summary>
        [Input("comparator", required: true)]
        public Input<string> Comparator { get; set; } = null!;

        /// <summary>
        /// The [comparison attribute](https://configcat.com/docs/advanced/targeting/#attribute) of the Segment.
        /// </summary>
        [Input("comparisonAttribute", required: true)]
        public Input<string> ComparisonAttribute { get; set; } = null!;

        /// <summary>
        /// The [comparison value](https://configcat.com/docs/advanced/targeting/#comparison-value) of the Segment.
        /// </summary>
        [Input("comparisonValue", required: true)]
        public Input<string> ComparisonValue { get; set; } = null!;

        /// <summary>
        /// The description of the Segment.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The name of the Segment.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the Product.
        /// </summary>
        [Input("productId", required: true)]
        public Input<string> ProductId { get; set; } = null!;

        public SegmentArgs()
        {
        }
        public static new SegmentArgs Empty => new SegmentArgs();
    }

    public sealed class SegmentState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The [comparator](https://configcat.com/docs/advanced/targeting/#comparator) of the Segment.
        /// </summary>
        [Input("comparator")]
        public Input<string>? Comparator { get; set; }

        /// <summary>
        /// The [comparison attribute](https://configcat.com/docs/advanced/targeting/#attribute) of the Segment.
        /// </summary>
        [Input("comparisonAttribute")]
        public Input<string>? ComparisonAttribute { get; set; }

        /// <summary>
        /// The [comparison value](https://configcat.com/docs/advanced/targeting/#comparison-value) of the Segment.
        /// </summary>
        [Input("comparisonValue")]
        public Input<string>? ComparisonValue { get; set; }

        /// <summary>
        /// The description of the Segment.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The name of the Segment.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the Product.
        /// </summary>
        [Input("productId")]
        public Input<string>? ProductId { get; set; }

        public SegmentState()
        {
        }
        public static new SegmentState Empty => new SegmentState();
    }
}
