// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Configcat.Outputs
{

    [OutputType]
    public sealed class GetPermissionGroupsPermissionGroupEnvironmentAccessResult
    {
        /// <summary>
        /// Represent the environment specific Feature Management permission. Possible values: full, readOnly, none
        /// </summary>
        public readonly string EnvironmentAccesstype;
        /// <summary>
        /// The unique [Environment](https://configcat.com/docs/main-concepts/#environment) ID.
        /// </summary>
        public readonly string EnvironmentId;

        [OutputConstructor]
        private GetPermissionGroupsPermissionGroupEnvironmentAccessResult(
            string environmentAccesstype,

            string environmentId)
        {
            EnvironmentAccesstype = environmentAccesstype;
            EnvironmentId = environmentId;
        }
    }
}
