// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Configcat.Outputs
{

    [OutputType]
    public sealed class GetProductsProductResult
    {
        /// <summary>
        /// The description of the Product.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The name of the Product.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The order of the Product within an Organization (zero-based).
        /// </summary>
        public readonly int Order;
        /// <summary>
        /// The unique Product ID.
        /// </summary>
        public readonly string ProductId;

        [OutputConstructor]
        private GetProductsProductResult(
            string description,

            string name,

            int order,

            string productId)
        {
            Description = description;
            Name = name;
            Order = order;
            ProductId = productId;
        }
    }
}
