// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Configcat.Outputs
{

    [OutputType]
    public sealed class GetSettingsSettingResult
    {
        /// <summary>
        /// The hint of the Setting.
        /// </summary>
        public readonly string Hint;
        /// <summary>
        /// The key of the Feature Flag/Setting.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The name of the Setting.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The unique Setting ID.
        /// </summary>
        public readonly string SettingId;
        /// <summary>
        /// The Setting's type. Available values: `boolean`|`string`|`int`|`double`.
        /// </summary>
        public readonly string SettingType;

        [OutputConstructor]
        private GetSettingsSettingResult(
            string hint,

            string key,

            string name,

            string settingId,

            string settingType)
        {
            Hint = hint;
            Key = key;
            Name = name;
            SettingId = settingId;
            SettingType = settingType;
        }
    }
}
