// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Configcat.Outputs
{

    [OutputType]
    public sealed class SettingValueV2TargetingRule
    {
        /// <summary>
        /// The conditions that are combined with the AND logical operator.
        /// </summary>
        public readonly ImmutableArray<Outputs.SettingValueV2TargetingRuleCondition> Conditions;
        /// <summary>
        /// The percentage options from where the evaluation process will choose a value based on the flag's percentage evaluation attribute.
        /// </summary>
        public readonly ImmutableArray<Outputs.SettingValueV2TargetingRulePercentageOption> PercentageOptions;
        /// <summary>
        /// Represents the value of a Feature Flag or Setting.
        /// </summary>
        public readonly Outputs.SettingValueV2TargetingRuleValue? Value;

        [OutputConstructor]
        private SettingValueV2TargetingRule(
            ImmutableArray<Outputs.SettingValueV2TargetingRuleCondition> conditions,

            ImmutableArray<Outputs.SettingValueV2TargetingRulePercentageOption> percentageOptions,

            Outputs.SettingValueV2TargetingRuleValue? value)
        {
            Conditions = conditions;
            PercentageOptions = percentageOptions;
            Value = value;
        }
    }
}
