// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package configcat

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-configcat/sdk/v5/go/configcat/internal"
)

// Use this data source to access information about existing **Permission Groups**. [What is a Permission Group in ConfigCat?](https://configcat.com/docs/advanced/team-management/team-management-basics/#permissions--permission-groups-product-level)
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
//	"github.com/pulumiverse/pulumi-configcat/sdk/v5/go/configcat"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			cfg := config.New(ctx, "")
//			productId := cfg.Require("productId")
//			myPermissionGroups, err := configcat.GetPermissionGroups(ctx, &configcat.GetPermissionGroupsArgs{
//				ProductId:       productId,
//				NameFilterRegex: pulumi.StringRef("Administrators"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("permissionGroupId", myPermissionGroups.PermissionGroups[0].PermissionGroupId)
//			return nil
//		})
//	}
//
// ```
func GetPermissionGroups(ctx *pulumi.Context, args *GetPermissionGroupsArgs, opts ...pulumi.InvokeOption) (*GetPermissionGroupsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPermissionGroupsResult
	err := ctx.Invoke("configcat:index/getPermissionGroups:getPermissionGroups", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPermissionGroups.
type GetPermissionGroupsArgs struct {
	// Filter the Permission Groups by name.
	NameFilterRegex *string `pulumi:"nameFilterRegex"`
	// The ID of the Product.
	ProductId string `pulumi:"productId"`
}

// A collection of values returned by getPermissionGroups.
type GetPermissionGroupsResult struct {
	// Internal ID of the data source. Do not use.
	Id string `pulumi:"id"`
	// Filter the Permission Groups by name.
	NameFilterRegex  *string                              `pulumi:"nameFilterRegex"`
	PermissionGroups []GetPermissionGroupsPermissionGroup `pulumi:"permissionGroups"`
	// The ID of the Product.
	ProductId string `pulumi:"productId"`
}

func GetPermissionGroupsOutput(ctx *pulumi.Context, args GetPermissionGroupsOutputArgs, opts ...pulumi.InvokeOption) GetPermissionGroupsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetPermissionGroupsResultOutput, error) {
			args := v.(GetPermissionGroupsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("configcat:index/getPermissionGroups:getPermissionGroups", args, GetPermissionGroupsResultOutput{}, options).(GetPermissionGroupsResultOutput), nil
		}).(GetPermissionGroupsResultOutput)
}

// A collection of arguments for invoking getPermissionGroups.
type GetPermissionGroupsOutputArgs struct {
	// Filter the Permission Groups by name.
	NameFilterRegex pulumi.StringPtrInput `pulumi:"nameFilterRegex"`
	// The ID of the Product.
	ProductId pulumi.StringInput `pulumi:"productId"`
}

func (GetPermissionGroupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPermissionGroupsArgs)(nil)).Elem()
}

// A collection of values returned by getPermissionGroups.
type GetPermissionGroupsResultOutput struct{ *pulumi.OutputState }

func (GetPermissionGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPermissionGroupsResult)(nil)).Elem()
}

func (o GetPermissionGroupsResultOutput) ToGetPermissionGroupsResultOutput() GetPermissionGroupsResultOutput {
	return o
}

func (o GetPermissionGroupsResultOutput) ToGetPermissionGroupsResultOutputWithContext(ctx context.Context) GetPermissionGroupsResultOutput {
	return o
}

// Internal ID of the data source. Do not use.
func (o GetPermissionGroupsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPermissionGroupsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Filter the Permission Groups by name.
func (o GetPermissionGroupsResultOutput) NameFilterRegex() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetPermissionGroupsResult) *string { return v.NameFilterRegex }).(pulumi.StringPtrOutput)
}

func (o GetPermissionGroupsResultOutput) PermissionGroups() GetPermissionGroupsPermissionGroupArrayOutput {
	return o.ApplyT(func(v GetPermissionGroupsResult) []GetPermissionGroupsPermissionGroup { return v.PermissionGroups }).(GetPermissionGroupsPermissionGroupArrayOutput)
}

// The ID of the Product.
func (o GetPermissionGroupsResultOutput) ProductId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPermissionGroupsResult) string { return v.ProductId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPermissionGroupsResultOutput{})
}
