// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package configcat

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-configcat/sdk/v5/go/configcat/internal"
)

func GetSettings(ctx *pulumi.Context, args *GetSettingsArgs, opts ...pulumi.InvokeOption) (*GetSettingsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetSettingsResult
	err := ctx.Invoke("configcat:index/getSettings:getSettings", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSettings.
type GetSettingsArgs struct {
	ConfigId       string  `pulumi:"configId"`
	KeyFilterRegex *string `pulumi:"keyFilterRegex"`
}

// A collection of values returned by getSettings.
type GetSettingsResult struct {
	ConfigId       string               `pulumi:"configId"`
	Id             string               `pulumi:"id"`
	KeyFilterRegex *string              `pulumi:"keyFilterRegex"`
	Settings       []GetSettingsSetting `pulumi:"settings"`
}

func GetSettingsOutput(ctx *pulumi.Context, args GetSettingsOutputArgs, opts ...pulumi.InvokeOption) GetSettingsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSettingsResultOutput, error) {
			args := v.(GetSettingsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("configcat:index/getSettings:getSettings", args, GetSettingsResultOutput{}, options).(GetSettingsResultOutput), nil
		}).(GetSettingsResultOutput)
}

// A collection of arguments for invoking getSettings.
type GetSettingsOutputArgs struct {
	ConfigId       pulumi.StringInput    `pulumi:"configId"`
	KeyFilterRegex pulumi.StringPtrInput `pulumi:"keyFilterRegex"`
}

func (GetSettingsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSettingsArgs)(nil)).Elem()
}

// A collection of values returned by getSettings.
type GetSettingsResultOutput struct{ *pulumi.OutputState }

func (GetSettingsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSettingsResult)(nil)).Elem()
}

func (o GetSettingsResultOutput) ToGetSettingsResultOutput() GetSettingsResultOutput {
	return o
}

func (o GetSettingsResultOutput) ToGetSettingsResultOutputWithContext(ctx context.Context) GetSettingsResultOutput {
	return o
}

func (o GetSettingsResultOutput) ConfigId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSettingsResult) string { return v.ConfigId }).(pulumi.StringOutput)
}

func (o GetSettingsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSettingsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSettingsResultOutput) KeyFilterRegex() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetSettingsResult) *string { return v.KeyFilterRegex }).(pulumi.StringPtrOutput)
}

func (o GetSettingsResultOutput) Settings() GetSettingsSettingArrayOutput {
	return o.ApplyT(func(v GetSettingsResult) []GetSettingsSetting { return v.Settings }).(GetSettingsSettingArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSettingsResultOutput{})
}
