// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package configcat

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-configcat/sdk/v5/go/configcat/internal"
)

// The provider type for the configcat package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// ConfigCat Public Management API's `basePath`. Defaults to [https://api.configcat.com](https://api.configcat.com). This
	// can also be sourced from the `CONFIGCAT_BASE_PATH` Environment Variable.
	BasePath pulumi.StringPtrOutput `pulumi:"basePath"`
	// Get your `basicAuthPassword` at [ConfigCat Public API
	// credentials](https://app.configcat.com/my-account/public-api-credentials). This can also be sourced from the
	// `CONFIGCAT_BASIC_AUTH_PASSWORD` Environment Variable.
	BasicAuthPassword pulumi.StringPtrOutput `pulumi:"basicAuthPassword"`
	// Get your `basicAuthUsername` at [ConfigCat Public API
	// credentials](https://app.configcat.com/my-account/public-api-credentials). This can also be sourced from the
	// `CONFIGCAT_BASIC_AUTH_USERNAME` Environment Variable.
	BasicAuthUsername pulumi.StringPtrOutput `pulumi:"basicAuthUsername"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.BasePath == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "CONFIGCAT_BASE_PATH"); d != nil {
			args.BasePath = pulumi.StringPtr(d.(string))
		}
	}
	if args.BasicAuthPassword == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "CONFIGCAT_BASIC_AUTH_PASSWORD"); d != nil {
			args.BasicAuthPassword = pulumi.StringPtr(d.(string))
		}
	}
	if args.BasicAuthUsername == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "CONFIGCAT_BASIC_AUTH_USERNAME"); d != nil {
			args.BasicAuthUsername = pulumi.StringPtr(d.(string))
		}
	}
	if args.BasicAuthPassword != nil {
		args.BasicAuthPassword = pulumi.ToSecret(args.BasicAuthPassword).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"basicAuthPassword",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:configcat", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// ConfigCat Public Management API's `basePath`. Defaults to [https://api.configcat.com](https://api.configcat.com). This
	// can also be sourced from the `CONFIGCAT_BASE_PATH` Environment Variable.
	BasePath *string `pulumi:"basePath"`
	// Get your `basicAuthPassword` at [ConfigCat Public API
	// credentials](https://app.configcat.com/my-account/public-api-credentials). This can also be sourced from the
	// `CONFIGCAT_BASIC_AUTH_PASSWORD` Environment Variable.
	BasicAuthPassword *string `pulumi:"basicAuthPassword"`
	// Get your `basicAuthUsername` at [ConfigCat Public API
	// credentials](https://app.configcat.com/my-account/public-api-credentials). This can also be sourced from the
	// `CONFIGCAT_BASIC_AUTH_USERNAME` Environment Variable.
	BasicAuthUsername *string `pulumi:"basicAuthUsername"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// ConfigCat Public Management API's `basePath`. Defaults to [https://api.configcat.com](https://api.configcat.com). This
	// can also be sourced from the `CONFIGCAT_BASE_PATH` Environment Variable.
	BasePath pulumi.StringPtrInput
	// Get your `basicAuthPassword` at [ConfigCat Public API
	// credentials](https://app.configcat.com/my-account/public-api-credentials). This can also be sourced from the
	// `CONFIGCAT_BASIC_AUTH_PASSWORD` Environment Variable.
	BasicAuthPassword pulumi.StringPtrInput
	// Get your `basicAuthUsername` at [ConfigCat Public API
	// credentials](https://app.configcat.com/my-account/public-api-credentials). This can also be sourced from the
	// `CONFIGCAT_BASIC_AUTH_USERNAME` Environment Variable.
	BasicAuthUsername pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// ConfigCat Public Management API's `basePath`. Defaults to [https://api.configcat.com](https://api.configcat.com). This
// can also be sourced from the `CONFIGCAT_BASE_PATH` Environment Variable.
func (o ProviderOutput) BasePath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.BasePath }).(pulumi.StringPtrOutput)
}

// Get your `basicAuthPassword` at [ConfigCat Public API
// credentials](https://app.configcat.com/my-account/public-api-credentials). This can also be sourced from the
// `CONFIGCAT_BASIC_AUTH_PASSWORD` Environment Variable.
func (o ProviderOutput) BasicAuthPassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.BasicAuthPassword }).(pulumi.StringPtrOutput)
}

// Get your `basicAuthUsername` at [ConfigCat Public API
// credentials](https://app.configcat.com/my-account/public-api-credentials). This can also be sourced from the
// `CONFIGCAT_BASIC_AUTH_USERNAME` Environment Variable.
func (o ProviderOutput) BasicAuthUsername() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.BasicAuthUsername }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
