// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Configcat.Inputs
{

    public sealed class SettingValueV2TargetingRuleConditionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Describes a condition that is based on a prerequisite flag.
        /// </summary>
        [Input("prerequisiteFlagCondition")]
        public Input<Inputs.SettingValueV2TargetingRuleConditionPrerequisiteFlagConditionArgs>? PrerequisiteFlagCondition { get; set; }

        /// <summary>
        /// Describes a condition that is based on a segment.
        /// </summary>
        [Input("segmentCondition")]
        public Input<Inputs.SettingValueV2TargetingRuleConditionSegmentConditionArgs>? SegmentCondition { get; set; }

        /// <summary>
        /// Describes a condition that is based on user attributes.
        /// </summary>
        [Input("userCondition")]
        public Input<Inputs.SettingValueV2TargetingRuleConditionUserConditionArgs>? UserCondition { get; set; }

        public SettingValueV2TargetingRuleConditionArgs()
        {
        }
        public static new SettingValueV2TargetingRuleConditionArgs Empty => new SettingValueV2TargetingRuleConditionArgs();
    }
}
