// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Configcat.Inputs
{

    public sealed class SettingValueV2TargetingRuleConditionSegmentConditionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The segment comparison operator used during the evaluation process. Possible values: `isIn`,`isNotIn`
        /// </summary>
        [Input("comparator", required: true)]
        public Input<string> Comparator { get; set; } = null!;

        /// <summary>
        /// The segment's identifier.
        /// </summary>
        [Input("segmentId", required: true)]
        public Input<string> SegmentId { get; set; } = null!;

        public SettingValueV2TargetingRuleConditionSegmentConditionArgs()
        {
        }
        public static new SettingValueV2TargetingRuleConditionSegmentConditionArgs Empty => new SettingValueV2TargetingRuleConditionSegmentConditionArgs();
    }
}
