// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the configcat package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'configcat';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Provider.__pulumiType;
    }

    /**
     * ConfigCat Public Management API Base Path (defaults to production).
     */
    public readonly basePath!: pulumi.Output<string | undefined>;
    /**
     * ConfigCat Public API credential - Basic Auth Password
     */
    public readonly basicAuthPassword!: pulumi.Output<string>;
    /**
     * ConfigCat Public API credential - Basic Auth Username.
     */
    public readonly basicAuthUsername!: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if ((!args || args.basicAuthPassword === undefined) && !opts.urn) {
                throw new Error("Missing required property 'basicAuthPassword'");
            }
            if ((!args || args.basicAuthUsername === undefined) && !opts.urn) {
                throw new Error("Missing required property 'basicAuthUsername'");
            }
            resourceInputs["basePath"] = args ? args.basePath : undefined;
            resourceInputs["basicAuthPassword"] = args ? args.basicAuthPassword : undefined;
            resourceInputs["basicAuthUsername"] = args ? args.basicAuthUsername : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * ConfigCat Public Management API Base Path (defaults to production).
     */
    basePath?: pulumi.Input<string>;
    /**
     * ConfigCat Public API credential - Basic Auth Password
     */
    basicAuthPassword: pulumi.Input<string>;
    /**
     * ConfigCat Public API credential - Basic Auth Username.
     */
    basicAuthUsername: pulumi.Input<string>;
}
